version: "3.10"
services:
  zookeeper:
    image: zookeeper:3.6
  kafka:
    image: bitnami/kafka:3
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  app:
    build: ./services/app
    volumes:
      - ./services/app:/home/parkyes90/app
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "7000:8000"
